from typing import Protocol
from datetime import datetime
from uuid import UUID

from cwms_batch_events.core.auth.user.models import User
from cwms_batch_events.core.models import (
    JobRecord,
    JobStatus,
    ScriptCreate,
    ScriptRead,
    ScriptRunRequest,
    ScriptUpdate,
)


class JobDatabase(Protocol):
    def get_latest_jobs_for_offices(self, offices: list[str]) -> list[JobRecord]: ...
    def upgrade_script_configuration(self, script_id: UUID, actor: User) -> ScriptRead: ...
    def claim_scheduled_dispatch(self, job_id: UUID) -> bool: ...
    def claim_batch_refresh(self, job_id: UUID) -> bool: ...
    def record_batch_details(self, job_id: UUID, detail: dict, observed_at: datetime) -> None: ...
    def bind_external_job_id(
        self,
        job_id: UUID,
        external_job_id: str,
    ) -> None: ...
    def create_job(self, payload: ScriptRunRequest, user: User) -> JobRecord: ...
    def get_job_by_external_id(self, ext_job_id: str) -> JobRecord | None: ...
    def get_job_by_id(self, job_id: UUID) -> JobRecord | None: ...
    def get_jobs_for_offices(
        self, offices: list[str], limit: int | None = None, offset: int = 0, script_id: UUID | None = None
    ) -> list[JobRecord]: ...
    def count_jobs_for_offices(self, offices: list[str], script_id: UUID | None = None) -> int: ...
    def get_scripts_for_office(self, office: str) -> list[ScriptRead]: ...
    def remove_script_if_allowed(
        self, script_id: UUID, admin_offices: list[str]
    ) -> None: ...
    def retrieve_script_catalog(
        self, roles: dict[str, list[str]]
    ) -> list[ScriptRead]: ...
    def store_script(self, payload: ScriptCreate, actor: User | None = None) -> ScriptRead: ...
    def update_job_status(self, job_id: UUID, status: JobStatus) -> None: ...
    def update_script(
        self, script_id: UUID, payload: ScriptUpdate, admin_offices: list[str], actor: User | None = None
    ) -> ScriptRead: ...
